XDC: Add counter attribute annotation test
Signed-off-by: Tomasz Michalak <tmichalak@antmicro.com>

diff --git a/xdc-plugin/tests/Makefile b/xdc-plugin/tests/Makefile
--- a/xdc-plugin/tests/Makefile
+++ b/xdc-plugin/tests/Makefile
@@ -1,6 +1,34 @@
-TESTS = dummy
+TESTS = counter
 
 all: $(TESTS)
 
-dummy:
-	@echo $@ PASS
+define test_tpl =
+$(1): $(1).json
+	@python compare_output_json.py --json $$< --golden $(1)_golden.json; \
+	RETVAL=$$$$? ; \
+	if [ $$$$RETVAL -eq 0 ]; then \
+		echo "$(1) PASS"; \
+		true; \
+	else \
+		echo "$(1) FAIL"; \
+		false; \
+	fi
+
+$(1).json: $(1).v
+	PART_JSON=xc7a35tcsg324-1.json \
+	OUT_JSON=$(1).json \
+	INPUT_XDC_FILE=$(1).xdc \
+	yosys -p "tcl synth.tcl" $$< -l yosys.log
+
+update_$(1): $(1).json
+	@python compare_output_json.py --json $$< --golden $(1)_golden.json --update
+
+endef
+
+$(foreach test,$(TESTS),$(eval $(call test_tpl,$(test))))
+
+update: $(foreach test,$(TESTS),update_$(test))
+
+
+clean:
+	rm -rf *.log $(foreach test,$(TESTS),$(test).json)
